#!/usr/bin/env python3.5

"""
# filaswitch

G-code post processor for adding proper purge tower for 2 extruder - one hotend setup.

Disclaimer: i'm not responsible if anything, good or bad, happens due to use of this script.

Version 0.1
"""
import argparse
import os
import sys
import tkinter as tk
import tkinter.filedialog as fdialog
from tkinter.messagebox import showerror

#from slicer_cura import CuraPrintFile
#from slicer_kisslicer import KissPrintFile
from slicer_simplify3d import Simplify3dGCodeFile
#from slicer_slic3r import Slic3rPrintFile

from logger import Logger
from switch_tower import PEEK, PTFE, E3DV6, HW_CONFIGS
from switch_tower import AUTO, LEFT, RIGHT, TOP, BOTTOM, TOWER_POSITIONS

import utils

prog_dir = os.path.dirname(os.path.realpath(__file__))

status_file = os.path.join(prog_dir, '.status')
status = utils.load_status(status_file)


def detect_file_type(gcode_file, log):
    with open(gcode_file, 'r') as gf:
        line1 = gf.readline()
        if line1.startswith('; G-Code generated by Simplify3D(R)'):
            log.info("Detected Simplify3D format")
            return Simplify3dGCodeFile
        #elif line1.startswith('; KISSlicer'):
        #    log.info("Detected KISSlicer format")
        #    return KissPrintFile
        #elif line1.startswith('; CURA'):
        #    log.info("Detected Cura format")
        #    return CuraPrintFile
        #elif line1.startswith('; generated by Slic3r'):
        #    log.info("Detected Slic3r format")
        #    return Slic3rPrintFile

        else:
            log.error("No supported gcode file detected.")
            exit(1)


class TopFrame(tk.Frame):
    def __init__(self, logger, master=None, info_frame=None):
        super().__init__(master)
        self.log = logger
        self.master.title("FilaSwitch")
        self.master.rowconfigure(6, weight=1)
        self.master.columnconfigure(5, weight=1)

        self.info_frame = info_frame
        self.grid(row=0, column=0, columnspan=5)
        self.create_widgets()

    def create_widgets(self):

        # labels
        self.hwlabel = tk.Label(self, text="1. Select HW config").grid(row=0, column=0, sticky=tk.W)
        self.position_label = tk.Label(self, text="2. Select purge tower position").grid(row=1, column=0, sticky=tk.W)
        self.gc_label = tk.Label(self, text="3. Select g-code to process").grid(row=2, column=0, sticky=tk.W)

        self.hw_var = tk.StringVar(self)
        last_hwconfig = status.get("last_hwconfig")
        if last_hwconfig and last_hwconfig in HW_CONFIGS:
            self.hw_var.set(last_hwconfig)
        else:
            self.hw_var.set(PTFE)

        self.option = tk.OptionMenu(self, self.hw_var, *HW_CONFIGS)
        self.option.grid(row=0, column=1, sticky=tk.W)

        self.position_var = tk.StringVar(self)
        last_position = status.get("last_position")
        if last_position and last_position in TOWER_POSITIONS:
            self.position_var.set(last_position)
        else:
            self.position_var.set(AUTO)

        self.position_option = tk.OptionMenu(self, self.position_var, *TOWER_POSITIONS)
        self.position_option.grid(row=1, column=1, sticky=tk.W)

        self.f_button = tk.Button(self)
        self.f_button["text"] = "Browse..."
        self.f_button["command"] = self.load_file
        self.f_button.grid(row=2, column=1, sticky=tk.W)

        self.quit = tk.Button(self, text="QUIT", fg="red",
                              command=self.master.destroy)
        self.quit.grid(row=3, column=1, sticky=tk.W)

    def load_file(self):
        self.info_frame.update_status("----------------------")
        last_dir = status.get("last_dir")
        if last_dir and os.path.exists(status["last_dir"]):
            gcode_file = fdialog.askopenfilename(filetypes=(("G-code files", "*.gcode"), ("all files","*.*")),
                                                 initialdir=status["last_dir"])
        else:
            gcode_file = fdialog.askopenfilename(filetypes=(("G-code files", "*.gcode"), ("all files", "*.*")))

        if gcode_file:
            try:
                print_type = detect_file_type(gcode_file, self.log)
                pf = print_type(self.log, self.hw_var.get(), self.position_var.get())
                result_file = pf.process(gcode_file)
                if self.info_frame:
                    self.log.info("New file saved: %s" % result_file)
                # save last used dir for later use
                file_dir = os.path.dirname(gcode_file)
                status["last_dir"] = file_dir
                status["last_hwconfig"] = self.hw_var.get()
                status["last_position"] = self.position_var.get()
            except Exception as e:
                self.log.error(str(e))
                showerror("File open error", "Cannot open file %s" % gcode_file)
        else:
            self.log.info("Aborted")


class BottomFrame(tk.Frame):

    def __init__(self, master=None):
        super().__init__(master)
        self.grid(row=4)
        self.line_count = 0
        self.create_widgets()

    def create_widgets(self):
        self.scrollbar = tk.Scrollbar(self)
        self.scrollbar.grid(row=3,column=3)

        self.status = tk.Text(self, height=10, width=90, yscrollcommand=self.scrollbar.set)
        self.status.grid(row=3, columnspan=2)

        self.scrollbar.config(command=self.status.yview)
        self.update_status("Idling...")

    def update_status(self, text):
        self.status.configure(state=tk.NORMAL)
        self.status.insert(tk.END, text + os.linesep)
        self.status.configure(state=tk.DISABLED)
        if not self.status.see(tk.END):
            self.scrollbar.set(100, 0)
        self.line_count += 1


def main():

    if len(sys.argv) < 2:
        # GUI mode
        top = tk.Tk()
        #top.grid_rowconfigure(0, minsize=50)
        #top.grid_rowconfigure(1, minsize=50)
        # top.geometry("300x300+30+30")
        info = BottomFrame(master=top)
        log = Logger(prog_dir, gui=info)
        app = TopFrame(log, master=top, info_frame=info)
        top.mainloop()
        utils.save_status_file(status_file, status)
    else:
        parser = argparse.ArgumentParser()
        parser.add_argument("file", help="Path to g-code file to process")
        parser.add_argument("hw_config", help="Extruder/hotend configuration", choices=HW_CONFIGS)
        parser.add_argument("--debug", help="Show debug prints", action="store_true")
        parser.add_argument("--position", help="Purge tower position. Default Auto. Auto will try to find a position with enough free space for the tower",
                            choices=TOWER_POSITIONS)
        args = parser.parse_args()

        log = Logger(prog_dir, gui=False, debug=args.debug)
        print_type = detect_file_type(args.file, log)
        pf = print_type(log, args.hw_config, args.position)
        result_file = pf.process(args.file)
        log.info("New file saved: %s" % result_file)


if __name__ == "__main__":
    main()