#!/usr/bin/env python3.5

"""
# filaswitch

G-code post processor for adding proper purge tower for 2 extruder - one hotend setup.

Disclaimer: i'm not responsible if anything, good or bad, happens due to use of this script.

Version 0.1
"""

import os
import sys
import tkinter as tk
import tkinter.filedialog as fdialog
from tkinter.messagebox import showerror

#from slicer_cura import CuraPrintFile
#from slicer_kisslicer import KissPrintFile
from slicer_simplify3d import Simplify3dGCodeFile
#from slicer_slic3r import Slic3rPrintFile

from logger import Logger

import utils

dir = os.path.dirname(os.path.realpath(__file__))

status_file = os.path.join(dir, '.status')
status = utils.load_status(status_file)

def detect_file_type(gcode_file, log):
    with open(gcode_file, 'r') as gf:
        line1 = gf.readline()
        if line1.startswith('; G-Code generated by Simplify3D(R)'):
            log.info("Detected Simplify3D format")
            return Simplify3dGCodeFile
        #elif line1.startswith('; KISSlicer'):
        #    log.info("Detected KISSlicer format")
        #    return KissPrintFile
        #elif line1.startswith('; CURA'):
        #    log.info("Detected Cura format")
        #    return CuraPrintFile
        #elif line1.startswith('; generated by Slic3r'):
        #    log.info("Detected Slic3r format")
        #    return Slic3rPrintFile

        else:
            log.error("No supported gcode file detected.")
            exit(1)


class TopFrame(tk.Frame):
    def __init__(self, logger, master=None, info_frame=None):
        super().__init__(master)
        self.log = logger
        self.master.title("FilaSwitch")
        self.master.rowconfigure(5, weight=1)
        self.master.columnconfigure(5, weight=1)
        #self.grid(sticky=tk.W + tk.E + tk.N + tk.S)

        self.info_frame = info_frame

        self.pack()
        self.create_widgets()

    def create_widgets(self):
        self.f_button = tk.Button(self,padx=10, pady=10)
        self.f_button["text"] = "Select g-code file..."
        self.f_button["command"] = self.load_file
        self.f_button.pack(side="top", pady=5)

        self.quit = tk.Button(self, text="QUIT", fg="red",
                              command=self.master.destroy)
        self.quit.pack(side="bottom", pady=5)

    def load_file(self):
        last_dir = status.get("last_dir")
        if last_dir and os.path.exists(status["last_dir"]):
            gcode_file = fdialog.askopenfilename(filetypes=(("G-code files", "*.gcode"), ("all files","*.*")),
                                                 initialdir=status["last_dir"])
        else:
            gcode_file = fdialog.askopenfilename(filetypes=(("G-code files", "*.gcode"), ("all files", "*.*")))

        if gcode_file:
            try:
                print_type = detect_file_type(gcode_file, self.log)
                pf = print_type(self.log)
                result_file = pf.process(gcode_file)
                if self.info_frame:
                    self.log.info("New file saved: %s" % result_file)
                # save last used dir for later use
                file_dir = os.path.dirname(gcode_file)
                status["last_dir"] = file_dir
            except Exception as e:
                self.log.error(str(e))
                showerror("File open error", "Cannot open file %s" % gcode_file)
            return


class BottomFrame(tk.Frame):

    def __init__(self, master=None):
        super().__init__(master)
        self.pack(side=tk.BOTTOM)
        self.create_widgets()

    def create_widgets(self):
        self.status = tk.Text(self, height=10, width=90)
        self.status.pack(side="bottom")
        self.update_status("Idling...")

    def update_status(self, text):
        self.status.insert(tk.END, text + os.linesep)


def main():
    debug = False
    if len(sys.argv) < 2:
        # GUI mode
        top = tk.Tk()
        # top.geometry("300x300+30+30")
        info = BottomFrame(master=top)
        log = Logger(dir, gui=info)
        app = TopFrame(log, master=top, info_frame=info)
        top.mainloop()
        utils.save_status_file(status_file, status)
    else:
        g_file = sys.argv[1]
        if len(sys.argv) == 3 and sys.argv[2] == "--debug":
            debug = True

        log = Logger(dir, gui=False, debug=debug)
        print_type = detect_file_type(g_file, log)
        pf = print_type(log)
        result_file = pf.process(g_file)
        log.info("New file saved: %s" % result_file)


if __name__ == "__main__":
    main()